name: Deploy HTML/CSS to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Deploy al branch gh-pages
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} gh-pages || mkdir gh-pages
          rm -rf gh-pages/*
          cp index.html styles.css gh-pages/
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy automático - ${{ github.sha }}"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin gh-pages
